KnownBottleMaxes = {
		"J2O": 12,
		"Magners": 10,
		"WKD": 14,
		"Smirnoff Ice": 14,
		"Efes": 5,
		"Hooch": 12,
		"Strathmore sparkling": 12,
		"Strathmore still": 18,
		"Beck’s Blue - Alcohol free": 6,
		"Beck’s": 12,
		"Budweiser": 10,
		"Brut": 4,
		"Blossom hill": 10,
		"Hardys Pinot Grigio": 15,
		"Limonata": 6,
		"Rossa": 6,
		"Old Jamaica": 6,
		"Adnams": 5,
		"Hardys Ros": 10,
		"Heineken 0.0": 6,
		"Lavazza": 7,
		"Dalston": 6,
		"Gunna": 6,
		"BrewDog": 5,
		"kombucha raspberry": 7,
		"Remedy kombucha cherry plum": 7,
		"coconut water": 7,
		"Fentimans tonic water": 23,
		"Fentimans light tonic water": 12,
		"Fentimans elderflower": 6,
		"Desperados": 12,
		"Corona": 12,
		"Sol": 12,
		"R White’s raspberry lemonade": 12,
		"cordial": 3,
		"Orange juice": 7,
		"Cranberry juice": 7,
		"Apple juice": 7,
		"Angry Orchard": 3,
		"Bulmers No 17 cider": 5,
		"Kopparberg Mixed Fruit cider": 5,
		"Tyskie Gronie": 5,
		"Baltika 7": 5,
		"Oakham Alpha Inception - West Coast IPA": 6,
		"Tsingtao": 5,
		"Birra Moretti": 5,
		"Newcastle Brown Ale": 10,
		"Villa Maria Sauvignon Blanc": 4,
		"Lagunitas IPA": 6,
		"Krombacher Pils": 5,
		"Hardys": 10,
		"Estrella Galicia": 12,
		"Trivento Malbec": 10,
		"Peroni": 7,
		"Kopparberg": 6,
	}